import React from 'react';

const Input = () => {
    return (
        <div class='mx-2'>
            Enter input to get <span class='text-primary'>Writing Assistant</span>
            <br />
            <div className='mt-2'>

                <div class='lg:flex justify-start grid md:grid-cols-1 '>
                    <div>
                        <div class=''>
                            Word Count: <input className='mx-4 border-2 border-neutral' type="number" value="8" min="1" max="8" ></input>

                            Prompt:

                            <select class="mx-4 border-2 border-primary border-neutral">

                                <option selected>Select</option>
                                <option value="US">United States</option>
                                <option value="CA">Canada</option>
                                <option value="FR">France</option>
                                <option value="DE">Germany</option>

                            </select>


                            Creativity:
                            <select class="mx-4  border-2 border-neutral">

                                <option selected>Select</option>
                                <option value="US">United States</option>
                                <option value="CA">Canada</option>
                                <option value="FR">France</option>
                                <option value="DE">Germany</option>

                            </select>
                        </div>
                    </div>
                    <div class='mx-52'>
                        <button class="py-3 px-20 mt-4 border-2 bg-primary text-white ">Write for me</button>
                    </div>
                </div>


                <div class='lg:flex justify-evenly grid md:grid-cols-1'>
                    <div>
                        <div class="mt-5 navbar shadow-2xl bg-base-100">
                            {/* <div class="flex-1">
                        <a class="btn btn-ghost normal-case text-xl">daisyUI</a>
                    </div> */}
                            <div class="flex-none">
                                <ul class="menu menu-horizontal p-0">
                                    <li><a class='font-bold shadow-lg'>B</a></li>
                                    <li><a class='font-bold shadow-lg'>I</a></li>
                                    <li><a>hyperlink</a></li>
                                    <li><a>text cut</a></li>
                                    <li><a>underline</a></li>
                                    <li><a>underline</a></li>
                                </ul>

                            </div>

                        </div>
                        <div class='bg-base-100'>
                            <p>
                                <p>As artificial intelligence continues to evolve, it is becoming increasingly capable of generating original and insightful content. This blog post is a prime example; the title was generated by AI within 10 seconds. AI is quickly becoming a powerful tool for content creators and marketers alike.</p>
                            </p>
                        </div>
                    </div>
                    <div>
                        <div class="mx-5 mt-5 navbar shadow-2xl bg-base-100">
                            {/* <div class="flex-1">
                        <a class="btn btn-ghost normal-case text-xl">daisyUI</a>
                    </div> */}

                            <div className='text-primary shadow-2xl'>
                                Copy
                            </div>

                            <div className='mx-2'>
                                <small>
                                    <p>
                                        As artificial intelligence continues to evolve, it is becoming increasingly capable of generating original and insightful content. This blog post is a prime example; the title was generated by AI within 10 seconds. AI is quickly becoming a powerful tool for content creators and marketers alike.
                                    </p>
                                </small>
                            </div>



                        </div>
                        <div class="mx-5 mt-5 navbar shadow-2xl bg-base-100">
                            {/* <div class="flex-1">
                        <a class="btn btn-ghost normal-case text-xl">daisyUI</a>
                    </div> */}

                            <div className='text-primary shadow-2xl'>
                                Copy
                            </div>

                            <div className='mx-2'>
                                <small>
                                    <p>
                                        As artificial intelligence continues to evolve, it is becoming increasingly capable of generating original and insightful content. This blog post is a prime example; the title was generated by AI within 10 seconds. AI is quickly becoming a powerful tool for content creators and marketers alike.
                                    </p>
                                </small>
                            </div>



                        </div>
                        <div class="mx-5 mt-5 navbar shadow-2xl bg-base-100">
                            {/* <div class="flex-1">
                        <a class="btn btn-ghost normal-case text-xl">daisyUI</a>
                    </div> */}

                            <div className='text-primary shadow-lg'>
                                Copy
                            </div>

                            <div className='mx-2'>
                                <small>
                                    <p>
                                        As artificial intelligence continues to evolve, it is becoming increasingly capable of generating original and insightful content. This blog post is a prime example; the title was generated by AI within 10 seconds. AI is quickly becoming a powerful tool for content creators and marketers alike.
                                    </p>
                                </small>
                            </div>



                        </div>
                    </div>

                </div>





            </div>
        </div>
    );
};

export default Input;